import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportDashboardReport = (
  stats: any
) => {
  const doc = new jsPDF();

  doc.setFontSize(24);
  doc.text(
    "SmartInfra GIS Report",
    14,
    20
  );

  doc.setFontSize(11);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    30
  );

  autoTable(doc, {
    startY: 40,

    head: [["Metric", "Value"]],

    body: [
      [
        "Total Assets",
        stats.totalAssets,
      ],
      [
        "Active Assets",
        stats.activeAssets,
      ],
      [
        "Maintenance Assets",
        stats.maintenanceAssets,
      ],
      [
        "Inactive Assets",
        stats.inactiveAssets,
      ],
      [
        "Total Tickets",
        stats.totalTickets,
      ],
    ],
  });

  doc.text(
    "Generated by SmartInfra GIS Platform",
    14,
    140
  );

  doc.save(
    `SmartInfra_Report_${Date.now()}.pdf`
  );
};